<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("productos")->insert(
          [
              [
                  'producto_id' => 1,
                  'nombre' => 'ACIDO ACETICO 20%',
                  'categoria_de_producto_id' => 3
              ],
              [
                  'producto_id' => 2,
                  'nombre' => 'ACIDO ACETICO 29% P/V',
                  'categoria_de_producto_id' => 3
              ],
              [
                  'producto_id' => 3,
                  'nombre' => 'ACIDO ACETICO GLACIAL',
                  'categoria_de_producto_id' => 3
              ],
              [
                  'producto_id' => 4,
                  'nombre' => 'ACIDO CLORHIDRICO 15%',
                  'categoria_de_producto_id' => 2
              ],
              [
                  'producto_id' => 5,
                  'nombre' => 'ACIDO CLORHIDRICO 19% P/V',
                  'categoria_de_producto_id' => 2
              ],
              [
                  'producto_id' => 6,
                  'nombre' => 'ACIDO CLORHIDRICO TEC. PURO',
                  'categoria_de_producto_id' => 2
              ],
              [
                  'producto_id' => 7,
                  'nombre' => 'ACIDO FOSFORICO 85%',
                  'categoria_de_producto_id' => 5
              ],
              [
                  'producto_id' => 8,
                  'nombre' => 'ACIDO NITRICO 50%',
                  'categoria_de_producto_id' => 4
              ],
              [
                  'producto_id' => 9,
                  'nombre' => 'ACIDO NITRICO 65%',
                  'categoria_de_producto_id' => 4
              ],
              [
                  'producto_id' => 10,
                  'nombre' => 'ACIDO SULFURICO 10%',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 11,
                  'nombre' => 'ACIDO SULFURICO 1200',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 12,
                  'nombre' => 'ACIDO SULFURICO 1205',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 13,
                  'nombre' => 'ACIDO SULFURICO 1210',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 14,
                  'nombre' => 'ACIDO SULFURICO 1220',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 15,
                  'nombre' => 'ACIDO SULFURICO 1230',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 16,
                  'nombre' => 'ACIDO SULFURICO 1245',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 17,
                  'nombre' => 'ACIDO SULFURICO 1250',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 18,
                  'nombre' => 'ACIDO SULFURICO 1280',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 19,
                  'nombre' => 'ACIDO SULFURICO 1285',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 20,
                  'nombre' => 'ACIDO SULFURICO 1290',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 21,
                  'nombre' => 'ACIDO SULFURICO 1300',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 22,
                  'nombre' => 'ACIDO SULFURICO 1320',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 23,
                  'nombre' => 'ACIDO SULFURICO 1340',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 24,
                  'nombre' => 'ACIDO SULFURICO 1400',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 25,
                  'nombre' => 'ACIDO SULFURICO 1500',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 26,
                  'nombre' => 'ACIDO SULFURICO 16%',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 27,
                  'nombre' => 'ACIDO SULFURICO 1700',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 28,
                  'nombre' => 'ACIDO SULFURICO 1840',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 29,
                  'nombre' => 'ACIDO SULFURICO 29% P/V',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 30,
                  'nombre' => 'ACIDO SULFURICO 94%',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 31,
                  'nombre' => 'ACIDO SULFURICO 98%',
                  'categoria_de_producto_id' => 1
              ],
              [
                  'producto_id' => 32,
                  'nombre' => 'AGUA AMONIACAL 19% P/V',
                  'categoria_de_producto_id' => 6
              ],
              [
                  'producto_id' => 33,
                  'nombre' => 'AGUA AMONIACAL 28%',
                  'categoria_de_producto_id' => 6
              ],
              [
                  'producto_id' => 34,
                  'nombre' => 'AGUA DESMINERALIZADA',
                  'categoria_de_producto_id' => 8
              ],
              [
                  'producto_id' => 35,
                  'nombre' => 'AGUA OXIGENADA 100 VOLUMENES',
                  'categoria_de_producto_id' => 7
              ],
              [
                  'producto_id' => 36,
                  'nombre' => 'AGUA OXIGENADA 130 VOLUMENES',
                  'categoria_de_producto_id' => 7
              ],
              [
                  'producto_id' => 37,
                  'nombre' => 'AGUA OXIGENADA 200 VOLUMENES',
                  'categoria_de_producto_id' => 7
              ],
              [
                  'producto_id' => 38,
                  'nombre' => 'AGUA OXIGENADA 250 VOLUMENES',
                  'categoria_de_producto_id' => 7
              ],
              [
                  'producto_id' => 39,
                  'nombre' => 'CLORURO FERRICO',
                  'categoria_de_producto_id' => 12
              ],
              [
                  'producto_id' => 40,
                  'nombre' => 'EFLUENTES INDUSTRIALES',
                  'categoria_de_producto_id' => 13
              ],
              [
                  'producto_id' => 41,
                  'nombre' => 'ELECTROLITO ALCALINO B-20',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 42,
                  'nombre' => 'ELECTROLITO ALCALINO B-5',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 43,
                  'nombre' => 'HIPOCLORITO DE SODIO',
                  'categoria_de_producto_id' => 9
              ],
              [
                  'producto_id' => 44,
                  'nombre' => 'POTASA CAUSTICA ESCAMA',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 45,
                  'nombre' => 'POTASA CAUSTICA LIQUIDA 29% P/V',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 46,
                  'nombre' => 'POTASA CAUSTICA LIQUIDA 46%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 47,
                  'nombre' => 'POTASA CAUSTICA LIQUIDA 50%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 48,
                  'nombre' => 'SODA CAUSTICA LIQUIDA 29% P/V',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 49,
                  'nombre' => 'SODA CAUSTICA LIQUIDA 30%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 50,
                  'nombre' => 'SODA CAUSTICA LIQUIDA 32%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 51,
                  'nombre' => 'SODA CAUSTICA LIQUIDA 40%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 52,
                  'nombre' => 'SODA CAUSTICA LIQUIDA 50%',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 53,
                  'nombre' => 'SODA CAUSTICA PERLA',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 54,
                  'nombre' => 'SODA SOLVAY 29% P/V',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 55,
                  'nombre' => 'SODA SOLVAY LIVIANA',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 56,
                  'nombre' => 'SULFATO DE ALUMINIO',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 57,
                  'nombre' => 'SULFATO DE COBRE PENTAHIDRATADO',
                  'categoria_de_producto_id' => 14
              ],
              [
                  'producto_id' => 58,
                  'nombre' => 'SULFATO FERROSO HERPTAHIDRATADO',
                  'categoria_de_producto_id' => 14
              ]
          ]
      );

      // Seeder de la relación muchos a muchos entre la tabla de productos con la tabla proveedores
      DB::table('proveedores_x_producto')->insert([
          ['producto_id' => 1, 'proveedor_id' => 18],
          ['producto_id' => 2, 'proveedor_id' => 18],
          ['producto_id' => 3, 'proveedor_id' => 1],
          ['producto_id' => 4, 'proveedor_id' => 18],
          ['producto_id' => 5, 'proveedor_id' => 18],
          ['producto_id' => 6, 'proveedor_id' => 10],
          ['producto_id' => 6, 'proveedor_id' => 15],
          ['producto_id' => 6, 'proveedor_id' => 17],
          ['producto_id' => 7, 'proveedor_id' => 7],
          ['producto_id' => 7, 'proveedor_id' => 8],
          ['producto_id' => 7, 'proveedor_id' => 13],
          ['producto_id' => 8, 'proveedor_id' => 4],
          ['producto_id' => 9, 'proveedor_id' => 4],
          ['producto_id' => 10, 'proveedor_id' => 18],
          ['producto_id' => 11, 'proveedor_id' => 18],
          ['producto_id' => 12, 'proveedor_id' => 18],
          ['producto_id' => 13, 'proveedor_id' => 18],
          ['producto_id' => 14, 'proveedor_id' => 18],
          ['producto_id' => 15, 'proveedor_id' => 18],
          ['producto_id' => 16, 'proveedor_id' => 18],
          ['producto_id' => 17, 'proveedor_id' => 18],
          ['producto_id' => 18, 'proveedor_id' => 18],
          ['producto_id' => 19, 'proveedor_id' => 18],
          ['producto_id' => 20, 'proveedor_id' => 18],
          ['producto_id' => 21, 'proveedor_id' => 18],
          ['producto_id' => 22, 'proveedor_id' => 18],
          ['producto_id' => 23, 'proveedor_id' => 18],
          ['producto_id' => 24, 'proveedor_id' => 18],
          ['producto_id' => 25, 'proveedor_id' => 18],
          ['producto_id' => 26, 'proveedor_id' => 18],
          ['producto_id' => 27, 'proveedor_id' => 18],
          ['producto_id' => 28, 'proveedor_id' => 18],
          ['producto_id' => 29, 'proveedor_id' => 18],
          ['producto_id' => 30, 'proveedor_id' => 18],
          ['producto_id' => 31, 'proveedor_id' => 4],
          ['producto_id' => 31, 'proveedor_id' => 5],
          ['producto_id' => 31, 'proveedor_id' => 7],
          ['producto_id' => 31, 'proveedor_id' => 9],
          ['producto_id' => 31, 'proveedor_id' => 12],
          ['producto_id' => 32, 'proveedor_id' => 7],
          ['producto_id' => 33, 'proveedor_id' => 7],
          ['producto_id' => 34, 'proveedor_id' => 14],
          ['producto_id' => 34, 'proveedor_id' => 18],
          ['producto_id' => 35, 'proveedor_id' => 18],
          ['producto_id' => 36, 'proveedor_id' => 18],
          ['producto_id' => 37, 'proveedor_id' => 18],
          ['producto_id' => 38, 'proveedor_id' => 1],
          ['producto_id' => 38, 'proveedor_id' => 2],
          ['producto_id' => 39, 'proveedor_id' => 11],
          ['producto_id' => 40, 'proveedor_id' => 18],
          ['producto_id' => 41, 'proveedor_id' => 18],
          ['producto_id' => 42, 'proveedor_id' => 18],
          ['producto_id' => 43, 'proveedor_id' => 15],
          ['producto_id' => 43, 'proveedor_id' => 16],
          ['producto_id' => 44, 'proveedor_id' => 3],
          ['producto_id' => 44, 'proveedor_id' => 6],
          ['producto_id' => 44, 'proveedor_id' => 7],
          ['producto_id' => 44, 'proveedor_id' => 13],
          ['producto_id' => 45, 'proveedor_id' => 18],
          ['producto_id' => 46, 'proveedor_id' => 18],
          ['producto_id' => 47, 'proveedor_id' => 8],
          ['producto_id' => 47, 'proveedor_id' => 13],
          ['producto_id' => 47, 'proveedor_id' => 18],
          ['producto_id' => 48, 'proveedor_id' => 18],
          ['producto_id' => 49, 'proveedor_id' => 18],
          ['producto_id' => 50, 'proveedor_id' => 18],
          ['producto_id' => 51, 'proveedor_id' => 18],
          ['producto_id' => 52, 'proveedor_id' => 10],
          ['producto_id' => 52, 'proveedor_id' => 15],
          ['producto_id' => 52, 'proveedor_id' => 17],
          ['producto_id' => 53, 'proveedor_id' => 6],
          ['producto_id' => 53, 'proveedor_id' => 7],
          ['producto_id' => 53, 'proveedor_id' => 13],
          ['producto_id' => 53, 'proveedor_id' => 17],
          ['producto_id' => 54, 'proveedor_id' => 18],
          ['producto_id' => 55, 'proveedor_id' => 6],
          ['producto_id' => 55, 'proveedor_id' => 13],
          ['producto_id' => 56, 'proveedor_id' => 13],
          ['producto_id' => 57, 'proveedor_id' => 13],
          ['producto_id' => 58, 'proveedor_id' => 13],

      ]);

      // Seeder de la relación muchos a muchos entre la tabla de productos con la tabla parametros
      DB::table('parametros_x_producto')->insert([
        ['producto_id' => 17, 'parametro_id' => 1],
        ['producto_id' => 20, 'parametro_id' => 1],
        ['producto_id' => 29, 'parametro_id' => 3],
        ['producto_id' => 27, 'parametro_id' => 1],
        ['producto_id' => 24, 'parametro_id' => 1],
        ['producto_id' => 21, 'parametro_id' => 1],
        ['producto_id' => 11, 'parametro_id' => 7],
        ['producto_id' => 12, 'parametro_id' => 7],
        ['producto_id' => 22, 'parametro_id' => 1],
        ['producto_id' => 13, 'parametro_id' => 9],
        ['producto_id' => 26, 'parametro_id' => 1],
        ['producto_id' => 14, 'parametro_id' => 1],
        ['producto_id' => 16, 'parametro_id' => 1],
        ['producto_id' => 10, 'parametro_id' => 1],
        ['producto_id' => 30, 'parametro_id' => 1],
        ['producto_id' => 28, 'parametro_id' => 15],
        ['producto_id' => 31, 'parametro_id' => 15],
        ['producto_id' => 18, 'parametro_id' => 1],
        ['producto_id' => 23, 'parametro_id' => 1],
        ['producto_id' => 19, 'parametro_id' => 1],
        ['producto_id' => 25, 'parametro_id' => 1],
        ['producto_id' => 2, 'parametro_id' => 21],
        ['producto_id' => 3, 'parametro_id' => 22],
        ['producto_id' => 50, 'parametro_id' => 23],
        ['producto_id' => 52, 'parametro_id' => 24],
        ['producto_id' => 51, 'parametro_id' => 25],
        ['producto_id' => 53, 'parametro_id' => 26],
        ['producto_id' => 48, 'parametro_id' => 27],
        ['producto_id' => 49, 'parametro_id' => 28],
        ['producto_id' => 6, 'parametro_id' => 29],
        ['producto_id' => 5, 'parametro_id' => 30],
        ['producto_id' => 4, 'parametro_id' => 31],
        ['producto_id' => 7, 'parametro_id' => 32],
        ['producto_id' => 7, 'parametro_id' => 33],
        ['producto_id' => 9, 'parametro_id' => 34],
        ['producto_id' => 8, 'parametro_id' => 35],
        ['producto_id' => 45, 'parametro_id' => 36],
        ['producto_id' => 46, 'parametro_id' => 37],
        ['producto_id' => 47, 'parametro_id' => 38],
        ['producto_id' => 44, 'parametro_id' => 39],
        ['producto_id' => 33, 'parametro_id' => 40],
        ['producto_id' => 32, 'parametro_id' => 41],
        ['producto_id' => 35, 'parametro_id' => 42],
        ['producto_id' => 36, 'parametro_id' => 43],
        ['producto_id' => 37, 'parametro_id' => 44],
        ['producto_id' => 38, 'parametro_id' => 45],
        ['producto_id' => 38, 'parametro_id' => 46],
        ['producto_id' => 37, 'parametro_id' => 47],
        ['producto_id' => 36, 'parametro_id' => 48],
        ['producto_id' => 35, 'parametro_id' => 49],
        ['producto_id' => 58, 'parametro_id' => 50],
        ['producto_id' => 39, 'parametro_id' => 51],
        ['producto_id' => 55, 'parametro_id' => 52],
        ['producto_id' => 54, 'parametro_id' => 53],
        ['producto_id' => 41, 'parametro_id' => 54],
        ['producto_id' => 42, 'parametro_id' => 55],
        ['producto_id' => 57, 'parametro_id' => 56],
        ['producto_id' => 43, 'parametro_id' => 57],
        ['producto_id' => 39, 'parametro_id' => 58],
        ['producto_id' => 17, 'parametro_id' => 59],
        ['producto_id' => 20, 'parametro_id' => 60],
        ['producto_id' => 25, 'parametro_id' => 61],
        ['producto_id' => 29, 'parametro_id' => 62],
        ['producto_id' => 15, 'parametro_id' => 63],
        ['producto_id' => 28, 'parametro_id' => 64],
        ['producto_id' => 31, 'parametro_id' => 64],
        ['producto_id' => 19, 'parametro_id' => 65],
        ['producto_id' => 27, 'parametro_id' => 66],
        ['producto_id' => 30, 'parametro_id' => 67],
        ['producto_id' => 18, 'parametro_id' => 68],
        ['producto_id' => 24, 'parametro_id' => 69],
        ['producto_id' => 21, 'parametro_id' => 70],
        ['producto_id' => 12, 'parametro_id' => 71],
        ['producto_id' => 13, 'parametro_id' => 71],
        ['producto_id' => 23, 'parametro_id' => 72],
        ['producto_id' => 11, 'parametro_id' => 73],
        ['producto_id' => 14, 'parametro_id' => 74],
        ['producto_id' => 26, 'parametro_id' => 75],
        ['producto_id' => 22, 'parametro_id' => 76],
        ['producto_id' => 10, 'parametro_id' => 77],
        ['producto_id' => 16, 'parametro_id' => 78],
        ['producto_id' => 2, 'parametro_id' => 79],
        ['producto_id' => 3, 'parametro_id' => 80],
        ['producto_id' => 50, 'parametro_id' => 81],
        ['producto_id' => 52, 'parametro_id' => 82],
        ['producto_id' => 51, 'parametro_id' => 83],
        ['producto_id' => 48, 'parametro_id' => 84],
        ['producto_id' => 49, 'parametro_id' => 85],
        ['producto_id' => 6, 'parametro_id' => 86],
        ['producto_id' => 5, 'parametro_id' => 87],
        ['producto_id' => 4, 'parametro_id' => 88],
        ['producto_id' => 7, 'parametro_id' => 89],
        ['producto_id' => 9, 'parametro_id' => 90],
        ['producto_id' => 8, 'parametro_id' => 91],
        ['producto_id' => 45, 'parametro_id' => 92],
        ['producto_id' => 46, 'parametro_id' => 93],
        ['producto_id' => 47, 'parametro_id' => 94],
        ['producto_id' => 33, 'parametro_id' => 95],
        ['producto_id' => 32, 'parametro_id' => 96],
        ['producto_id' => 35, 'parametro_id' => 97],
        ['producto_id' => 36, 'parametro_id' => 98],
        ['producto_id' => 37, 'parametro_id' => 99],
        ['producto_id' => 38, 'parametro_id' => 100],
        ['producto_id' => 39, 'parametro_id' => 101],
        ['producto_id' => 54, 'parametro_id' => 102],
        ['producto_id' => 41, 'parametro_id' => 103],
        ['producto_id' => 42, 'parametro_id' => 104],
        ['producto_id' => 43, 'parametro_id' => 105],
        ['producto_id' => 10, 'parametro_id' => 106],
        ['producto_id' => 11, 'parametro_id' => 106],
        ['producto_id' => 12, 'parametro_id' => 106],
        ['producto_id' => 13, 'parametro_id' => 106],
        ['producto_id' => 14, 'parametro_id' => 106],
        ['producto_id' => 15, 'parametro_id' => 106],
        ['producto_id' => 16, 'parametro_id' => 106],
        ['producto_id' => 17, 'parametro_id' => 106],
        ['producto_id' => 18, 'parametro_id' => 106],
        ['producto_id' => 19, 'parametro_id' => 106],
        ['producto_id' => 20, 'parametro_id' => 106],
        ['producto_id' => 21, 'parametro_id' => 106],
        ['producto_id' => 22, 'parametro_id' => 106],
        ['producto_id' => 23, 'parametro_id' => 106],
        ['producto_id' => 24, 'parametro_id' => 106],
        ['producto_id' => 25, 'parametro_id' => 106],
        ['producto_id' => 26, 'parametro_id' => 106],
        ['producto_id' => 27, 'parametro_id' => 106],
        ['producto_id' => 28, 'parametro_id' => 106],
        ['producto_id' => 29, 'parametro_id' => 106],
        ['producto_id' => 30, 'parametro_id' => 106],
        ['producto_id' => 31, 'parametro_id' => 106],
        ['producto_id' => 2, 'parametro_id' => 107],
        ['producto_id' => 3, 'parametro_id' => 107],
        ['producto_id' => 48, 'parametro_id' => 108],
        ['producto_id' => 49, 'parametro_id' => 108],
        ['producto_id' => 50, 'parametro_id' => 108],
        ['producto_id' => 51, 'parametro_id' => 108],
        ['producto_id' => 52, 'parametro_id' => 108],
        ['producto_id' => 53, 'parametro_id' => 108],
        ['producto_id' => 4, 'parametro_id' => 109],
        ['producto_id' => 5, 'parametro_id' => 109],
        ['producto_id' => 6, 'parametro_id' => 109],
        ['producto_id' => 8, 'parametro_id' => 109],
        ['producto_id' => 7, 'parametro_id' => 110],
        ['producto_id' => 45, 'parametro_id' => 111],
        ['producto_id' => 46, 'parametro_id' => 111],
        ['producto_id' => 47, 'parametro_id' => 111],
        ['producto_id' => 44, 'parametro_id' => 112],
        ['producto_id' => 32, 'parametro_id' => 113],
        ['producto_id' => 33, 'parametro_id' => 113],
        ['producto_id' => 34, 'parametro_id' => 114],
        ['producto_id' => 41, 'parametro_id' => 115],
        ['producto_id' => 42, 'parametro_id' => 115],
        ['producto_id' => 57, 'parametro_id' => 116],
        ['producto_id' => 43, 'parametro_id' => 117],
        ['producto_id' => 10, 'parametro_id' => 118],
        ['producto_id' => 11, 'parametro_id' => 118],
        ['producto_id' => 12, 'parametro_id' => 118],
        ['producto_id' => 13, 'parametro_id' => 118],
        ['producto_id' => 14, 'parametro_id' => 118],
        ['producto_id' => 15, 'parametro_id' => 118],
        ['producto_id' => 16, 'parametro_id' => 118],
        ['producto_id' => 17, 'parametro_id' => 118],
        ['producto_id' => 18, 'parametro_id' => 118],
        ['producto_id' => 19, 'parametro_id' => 118],
        ['producto_id' => 20, 'parametro_id' => 118],
        ['producto_id' => 21, 'parametro_id' => 118],
        ['producto_id' => 22, 'parametro_id' => 118],
        ['producto_id' => 23, 'parametro_id' => 118],
        ['producto_id' => 24, 'parametro_id' => 118],
        ['producto_id' => 25, 'parametro_id' => 118],
        ['producto_id' => 26, 'parametro_id' => 118],
        ['producto_id' => 27, 'parametro_id' => 118],
        ['producto_id' => 28, 'parametro_id' => 118],
        ['producto_id' => 29, 'parametro_id' => 118],
        ['producto_id' => 30, 'parametro_id' => 118],
        ['producto_id' => 31, 'parametro_id' => 118],
        ['producto_id' => 32, 'parametro_id' => 118],
        ['producto_id' => 33, 'parametro_id' => 118],
        ['producto_id' => 34, 'parametro_id' => 118],
        ['producto_id' => 2, 'parametro_id' => 119],
        ['producto_id' => 3, 'parametro_id' => 119],
        ['producto_id' => 48, 'parametro_id' => 120],
        ['producto_id' => 49, 'parametro_id' => 120],
        ['producto_id' => 50, 'parametro_id' => 120],
        ['producto_id' => 51, 'parametro_id' => 120],
        ['producto_id' => 52, 'parametro_id' => 120],
        ['producto_id' => 53, 'parametro_id' => 120],
        ['producto_id' => 7, 'parametro_id' => 121],
        ['producto_id' => 8, 'parametro_id' => 121],
        ['producto_id' => 45, 'parametro_id' => 124],
        ['producto_id' => 46, 'parametro_id' => 124],
        ['producto_id' => 47, 'parametro_id' => 124],
        ['producto_id' => 44, 'parametro_id' => 125],
        ['producto_id' => 35, 'parametro_id' => 126],
        ['producto_id' => 36, 'parametro_id' => 126],
        ['producto_id' => 37, 'parametro_id' => 126],
        ['producto_id' => 38, 'parametro_id' => 126],
        ['producto_id' => 54, 'parametro_id' => 127],
        ['producto_id' => 55, 'parametro_id' => 127],
        ['producto_id' => 41, 'parametro_id' => 128],
        ['producto_id' => 42, 'parametro_id' => 128],
        ['producto_id' => 2, 'parametro_id' => 129],
        ['producto_id' => 3, 'parametro_id' => 129],
        ['producto_id' => 7, 'parametro_id' => 130],
        ['producto_id' => 35, 'parametro_id' => 131],
        ['producto_id' => 36, 'parametro_id' => 131],
        ['producto_id' => 37, 'parametro_id' => 131],
        ['producto_id' => 38, 'parametro_id' => 131],
        ['producto_id' => 56, 'parametro_id' => 132],
        ['producto_id' => 58, 'parametro_id' => 132],
        ['producto_id' => 57, 'parametro_id' => 133],
        ['producto_id' => 2, 'parametro_id' => 134],
        ['producto_id' => 3, 'parametro_id' => 134],
        ['producto_id' => 7, 'parametro_id' => 136],
        ['producto_id' => 48, 'parametro_id' => 137],
        ['producto_id' => 55, 'parametro_id' => 137],
        ['producto_id' => 56, 'parametro_id' => 138],
        ['producto_id' => 36, 'parametro_id' => 139],
        ['producto_id' => 37, 'parametro_id' => 140],
        ['producto_id' => 38, 'parametro_id' => 141],
        ['producto_id' => 35, 'parametro_id' => 142],
        ['producto_id' => 36, 'parametro_id' => 143],
        ['producto_id' => 37, 'parametro_id' => 144],
        ['producto_id' => 38, 'parametro_id' => 145],
        ['producto_id' => 48, 'parametro_id' => 146],
        ['producto_id' => 49, 'parametro_id' => 146],
        ['producto_id' => 50, 'parametro_id' => 146],
        ['producto_id' => 51, 'parametro_id' => 146],
        ['producto_id' => 52, 'parametro_id' => 146],
        ['producto_id' => 53, 'parametro_id' => 146],
        ['producto_id' => 45, 'parametro_id' => 147],
        ['producto_id' => 46, 'parametro_id' => 147],
        ['producto_id' => 47, 'parametro_id' => 147],
        ['producto_id' => 44, 'parametro_id' => 148],
        ['producto_id' => 41, 'parametro_id' => 149],
        ['producto_id' => 42, 'parametro_id' => 149],
        ['producto_id' => 53, 'parametro_id' => 150],
        ['producto_id' => 53, 'parametro_id' => 151],
        ['producto_id' => 45, 'parametro_id' => 152],
        ['producto_id' => 46, 'parametro_id' => 152],
        ['producto_id' => 47, 'parametro_id' => 152],
        ['producto_id' => 44, 'parametro_id' => 153],
        ['producto_id' => 43, 'parametro_id' => 154],
        ['producto_id' => 43, 'parametro_id' => 155],
        ['producto_id' => 2, 'parametro_id' => 156],
        ['producto_id' => 3, 'parametro_id' => 156],
        ['producto_id' => 4, 'parametro_id' => 156],
        ['producto_id' => 5, 'parametro_id' => 156],
        ['producto_id' => 6, 'parametro_id' => 156],
        ['producto_id' => 7, 'parametro_id' => 156],
        ['producto_id' => 10, 'parametro_id' => 156],
        ['producto_id' => 11, 'parametro_id' => 156],
        ['producto_id' => 12, 'parametro_id' => 156],
        ['producto_id' => 13, 'parametro_id' => 156],
        ['producto_id' => 14, 'parametro_id' => 156],
        ['producto_id' => 15, 'parametro_id' => 156],
        ['producto_id' => 16, 'parametro_id' => 156],
        ['producto_id' => 17, 'parametro_id' => 156],
        ['producto_id' => 18, 'parametro_id' => 156],
        ['producto_id' => 19, 'parametro_id' => 156],
        ['producto_id' => 20, 'parametro_id' => 156],
        ['producto_id' => 21, 'parametro_id' => 156],
        ['producto_id' => 22, 'parametro_id' => 156],
        ['producto_id' => 23, 'parametro_id' => 156],
        ['producto_id' => 24, 'parametro_id' => 156],
        ['producto_id' => 25, 'parametro_id' => 156],
        ['producto_id' => 26, 'parametro_id' => 156],
        ['producto_id' => 27, 'parametro_id' => 156],
        ['producto_id' => 28, 'parametro_id' => 156],
        ['producto_id' => 29, 'parametro_id' => 156],
        ['producto_id' => 30, 'parametro_id' => 156],
        ['producto_id' => 31, 'parametro_id' => 156],
        ['producto_id' => 32, 'parametro_id' => 156],
        ['producto_id' => 33, 'parametro_id' => 156],
        ['producto_id' => 34, 'parametro_id' => 156],
        ['producto_id' => 35, 'parametro_id' => 156],
        ['producto_id' => 36, 'parametro_id' => 156],
        ['producto_id' => 37, 'parametro_id' => 156],
        ['producto_id' => 38, 'parametro_id' => 156],
        ['producto_id' => 39, 'parametro_id' => 156],
        ['producto_id' => 41, 'parametro_id' => 156],
        ['producto_id' => 42, 'parametro_id' => 156],
        ['producto_id' => 43, 'parametro_id' => 156],
        ['producto_id' => 45, 'parametro_id' => 156],
        ['producto_id' => 46, 'parametro_id' => 156],
        ['producto_id' => 47, 'parametro_id' => 156],
        ['producto_id' => 48, 'parametro_id' => 156],
        ['producto_id' => 49, 'parametro_id' => 156],
        ['producto_id' => 50, 'parametro_id' => 156],
        ['producto_id' => 51, 'parametro_id' => 156],
        ['producto_id' => 52, 'parametro_id' => 156],
        ['producto_id' => 54, 'parametro_id' => 156],
        ['producto_id' => 55, 'parametro_id' => 157],
        ['producto_id' => 57, 'parametro_id' => 159],
        ['producto_id' => 44, 'parametro_id' => 160],
        ['producto_id' => 53, 'parametro_id' => 161],
        ['producto_id' => 56, 'parametro_id' => 162],
        ['producto_id' => 58, 'parametro_id' => 163],
        ['producto_id' => 10, 'parametro_id' => 164],
        ['producto_id' => 11, 'parametro_id' => 164],
        ['producto_id' => 12, 'parametro_id' => 164],
        ['producto_id' => 13, 'parametro_id' => 164],
        ['producto_id' => 14, 'parametro_id' => 164],
        ['producto_id' => 15, 'parametro_id' => 164],
        ['producto_id' => 16, 'parametro_id' => 164],
        ['producto_id' => 17, 'parametro_id' => 164],
        ['producto_id' => 18, 'parametro_id' => 164],
        ['producto_id' => 19, 'parametro_id' => 164],
        ['producto_id' => 20, 'parametro_id' => 164],
        ['producto_id' => 21, 'parametro_id' => 164],
        ['producto_id' => 22, 'parametro_id' => 164],
        ['producto_id' => 23, 'parametro_id' => 164],
        ['producto_id' => 24, 'parametro_id' => 164],
        ['producto_id' => 25, 'parametro_id' => 164],
        ['producto_id' => 26, 'parametro_id' => 164],
        ['producto_id' => 27, 'parametro_id' => 164],
        ['producto_id' => 28, 'parametro_id' => 164],
        ['producto_id' => 29, 'parametro_id' => 164],
        ['producto_id' => 30, 'parametro_id' => 164],
        ['producto_id' => 31, 'parametro_id' => 164],
        ['producto_id' => 45, 'parametro_id' => 164],
        ['producto_id' => 46, 'parametro_id' => 164],
        ['producto_id' => 47, 'parametro_id' => 164],
        ['producto_id' => 48, 'parametro_id' => 164],
        ['producto_id' => 49, 'parametro_id' => 164],
        ['producto_id' => 50, 'parametro_id' => 164],
        ['producto_id' => 51, 'parametro_id' => 164],
        ['producto_id' => 52, 'parametro_id' => 164],
        ['producto_id' => 4, 'parametro_id' => 165],
        ['producto_id' => 5, 'parametro_id' => 165],
        ['producto_id' => 6, 'parametro_id' => 165],
        ['producto_id' => 2, 'parametro_id' => 166],
        ['producto_id' => 3, 'parametro_id' => 166],
        ['producto_id' => 7, 'parametro_id' => 166],
        ['producto_id' => 8, 'parametro_id' => 166],
        ['producto_id' => 9, 'parametro_id' => 166],
        ['producto_id' => 32, 'parametro_id' => 166],
        ['producto_id' => 33, 'parametro_id' => 166],
        ['producto_id' => 34, 'parametro_id' => 166],
        ['producto_id' => 35, 'parametro_id' => 166],
        ['producto_id' => 36, 'parametro_id' => 166],
        ['producto_id' => 37, 'parametro_id' => 166],
        ['producto_id' => 38, 'parametro_id' => 166],
        ['producto_id' => 41, 'parametro_id' => 166],
        ['producto_id' => 42, 'parametro_id' => 166],
        ['producto_id' => 54, 'parametro_id' => 166],
        ['producto_id' => 58, 'parametro_id' => 167],
        ['producto_id' => 39, 'parametro_id' => 168],
        ['producto_id' => 43, 'parametro_id' => 169],
        ['producto_id' => 2, 'parametro_id' => 170],
        ['producto_id' => 3, 'parametro_id' => 170],
        ['producto_id' => 4, 'parametro_id' => 170],
        ['producto_id' => 5, 'parametro_id' => 170],
        ['producto_id' => 6, 'parametro_id' => 170],
        ['producto_id' => 7, 'parametro_id' => 170],
        ['producto_id' => 8, 'parametro_id' => 170],
        ['producto_id' => 9, 'parametro_id' => 170],
        ['producto_id' => 10, 'parametro_id' => 170],
        ['producto_id' => 11, 'parametro_id' => 170],
        ['producto_id' => 12, 'parametro_id' => 170],
        ['producto_id' => 13, 'parametro_id' => 170],
        ['producto_id' => 14, 'parametro_id' => 170],
        ['producto_id' => 15, 'parametro_id' => 170],
        ['producto_id' => 16, 'parametro_id' => 170],
        ['producto_id' => 17, 'parametro_id' => 170],
        ['producto_id' => 18, 'parametro_id' => 170],
        ['producto_id' => 19, 'parametro_id' => 170],
        ['producto_id' => 20, 'parametro_id' => 170],
        ['producto_id' => 21, 'parametro_id' => 170],
        ['producto_id' => 22, 'parametro_id' => 170],
        ['producto_id' => 23, 'parametro_id' => 170],
        ['producto_id' => 24, 'parametro_id' => 170],
        ['producto_id' => 25, 'parametro_id' => 170],
        ['producto_id' => 26, 'parametro_id' => 170],
        ['producto_id' => 27, 'parametro_id' => 170],
        ['producto_id' => 28, 'parametro_id' => 170],
        ['producto_id' => 29, 'parametro_id' => 170],
        ['producto_id' => 30, 'parametro_id' => 170],
        ['producto_id' => 31, 'parametro_id' => 170],
        ['producto_id' => 32, 'parametro_id' => 170],
        ['producto_id' => 33, 'parametro_id' => 170],
        ['producto_id' => 34, 'parametro_id' => 170],
        ['producto_id' => 35, 'parametro_id' => 170],
        ['producto_id' => 36, 'parametro_id' => 170],
        ['producto_id' => 37, 'parametro_id' => 170],
        ['producto_id' => 38, 'parametro_id' => 170],
        ['producto_id' => 39, 'parametro_id' => 170],
        ['producto_id' => 41, 'parametro_id' => 170],
        ['producto_id' => 42, 'parametro_id' => 170],
        ['producto_id' => 43, 'parametro_id' => 170],
        ['producto_id' => 45, 'parametro_id' => 170],
        ['producto_id' => 46, 'parametro_id' => 170],
        ['producto_id' => 47, 'parametro_id' => 170],
        ['producto_id' => 50, 'parametro_id' => 170],
        ['producto_id' => 56, 'parametro_id' => 170],
      ]);
    }
}
